apiVersion: v1
kind: Service                   # Resource type is Service
metadata:
  name: backend-service         # Name of the service
spec:
  selector:
    app: backend                # Selects pods with label app=backend to route traffic to
  type: NodePort                # Service type exposes the app on each node’s IP at a static port
  ports:
    - protocol: TCP             # Protocol used by the service
      port: 8081               # Port exposed by the service
      targetPort: 8081         # Port on the pod/container to forward traffic to
      nodePort: 30081          # Port on the node to expose the service externally
